name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   
    - name: Build Docker image and push it to GHRC
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: pwreverseproxy
        registry: ghcr.io
        username: myrkgard
        password: ${{ secrets.GITHUB_TOKEN }}
